name: Android Release CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Hub Release APK
      run: ./gradlew :app:assembleRelease

    - name: Build Panel Release APK
      run: ./gradlew :panel:assembleRelease

    - name: Upload Hub Release APK
      uses: actions/upload-artifact@v4
      with:
        name: WinlatorHub-Release
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload Panel Release APK
      uses: actions/upload-artifact@v4
      with:
        name: WinlatorPanel-Release
        path: ./panel/build/outputs/apk/release/panel-release-unsigned.apk
