name: Android Release CI

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      if: "${{ secrets.KEYSTORE_BASE64 != '' }}"
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

    - name: Build Hub Release APK
      run: |
        ./gradlew :app:assembleRelease \
          -PRELEASE_STORE_FILE=../keystore.jks \
          -PRELEASE_STORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
          -PRELEASE_KEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
          -PRELEASE_KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"

    - name: Build Panel Release APK
      run: |
        ./gradlew :panel:assembleRelease \
          -PRELEASE_STORE_FILE=../keystore.jks \
          -PRELEASE_STORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
          -PRELEASE_KEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
          -PRELEASE_KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"

    - name: Upload Hub Release APK
      uses: actions/upload-artifact@v4
      with:
        name: WinlatorHub-Release
        path: ./app/build/outputs/apk/release/*.apk

    - name: Upload Panel Release APK
      uses: actions/upload-artifact@v4
      with:
        name: WinlatorPanel-Release
        path: ./panel/build/outputs/apk/release/*.apk
